# Netlify Configuration for Society Management System
# This file configures build settings, redirects, and security headers for Netlify deployment

[build]
  # Build command - since this is a static site, we just copy files
  command = "echo 'Building Society Management System...' && npm run build || echo 'Static build complete'"
  
  # Publish directory - the root directory contains our static files
  publish = "."
  
  # Functions directory (if we add Netlify functions later)
  functions = "netlify/functions"

# Environment variables for different deploy contexts
[build.environment]
  VITE_BUILD_TARGET = "netlify"
  VITE_APP_ENV = "production"
  VITE_ENABLE_PWA = "true"
  VITE_ENABLE_SERVICE_WORKER = "true"
  VITE_ENABLE_DEV_TOOLS = "false"
  VITE_ENABLE_CONSOLE_LOGGING = "false"
  VITE_ENABLE_SECURITY_LOGGING = "true"
  VITE_ENABLE_RATE_LIMITING = "true"
  VITE_ENABLE_SESSION_MONITORING = "true"
  VITE_ENABLE_SESSION_ENCRYPTION = "true"
  VITE_ENABLE_CSRF_PROTECTION = "true"

# Production build settings
[context.production]
  command = "echo 'Production build for Society Management System'"
  [context.production.environment]
    VITE_APP_ENV = "production"
    VITE_DEPLOY_CONTEXT = "production"
    VITE_ENABLE_ANALYTICS = "true"
    VITE_ENABLE_ERROR_REPORTING = "true"

# Deploy preview settings
[context.deploy-preview]
  command = "echo 'Deploy preview build'"
  [context.deploy-preview.environment]
    VITE_APP_ENV = "staging"
    VITE_DEPLOY_CONTEXT = "deploy-preview"
    VITE_ENABLE_DEV_TOOLS = "true"
    VITE_ENABLE_CONSOLE_LOGGING = "true"

# Branch deploys
[context.branch-deploy]
  command = "echo 'Branch deploy build'"
  [context.branch-deploy.environment]
    VITE_APP_ENV = "development"
    VITE_DEPLOY_CONTEXT = "branch-deploy"
    VITE_ENABLE_DEV_TOOLS = "true"
    VITE_ENABLE_CONSOLE_LOGGING = "true"

# Redirects and rewrites
[[redirects]]
  # SPA fallback - serve index.html for any non-file requests
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Role = [""], Country = [""] }

[[redirects]]
  # PWA offline fallback
  from = "/offline"
  to = "/index.html"
  status = 200

[[redirects]]
  # API redirects (if you add backend functions)
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers for PWA and general security
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=()"
    
    # Content Security Policy
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' cdn.jsdelivr.net cdnjs.cloudflare.com *.supabase.co;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: *.supabase.co;
      font-src 'self';
      connect-src 'self' *.supabase.co wss://*.supabase.co;
      media-src 'self';
      object-src 'none';
      child-src 'none';
      worker-src 'self';
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
      manifest-src 'self';
    '''
    
    # HSTS for HTTPS enforcement
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# PWA specific headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

# Static asset caching
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files - no cache for dynamic content
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Security for sensitive files
[[headers]]
  for = "/.env*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, nosnippet, noarchive"

# Edge functions (if needed in the future)
# [[edge_functions]]
#   function = "auth-check"
#   path = "/admin/*"

# Build plugins (if needed)
# [[plugins]]
#   package = "@netlify/plugin-sitemap"

# Form handling (if you add contact forms)
# [[forms]]
#   name = "contact"
#   action = "/thank-you"